--------------------------------------------------------
--  Arquivo criado - terça-feira-setembro-20-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View VW_ACCOUNT_STATEMENTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "STFDEV"."VW_ACCOUNT_STATEMENTS" ("LANCAMENTO", "CPF/CNPJ", "CLIENTE", "TRANSACAO", "VALOR R$", "SALDO ATUALIZADO R$") AS 
  SELECT S.RELEASE_DATE AS "LANCAMENTO", M.CPF AS "CPF/CNPJ",
M.FULL_NAME AS CLIENTE, S.T_DESCRIPTION AS TRANSACAO, 
TO_CHAR(S.AMOUNT,'9990D00')||' '||S.AMOUNT_TYPE AS "VALOR R$", 
TO_CHAR(
    SUM(CASE 
        WHEN S.AMOUNT_TYPE = 'C' THEN S.AMOUNT 
        ELSE -S.AMOUNT 
        END)
    OVER(PARTITION BY M.CPF ORDER BY S.RELEASE_DATE 
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), '999999D00')||' C' AS "SALDO ATUALIZADO R$"
FROM MOTOBOYS M 
INNER JOIN BANK_STATEMENTS S ON M.ACCOUNT_NUMBER = S.ACCOUNT_NUMBER
WHERE S.RELEASE_DATE <= SYSDATE
UNION
SELECT S.RELEASE_DATE, C.CNPJ, C.COMPANY_NAME, S.T_DESCRIPTION, 
TO_CHAR(S.AMOUNT,'9990D00')||' '||S.AMOUNT_TYPE, 
TO_CHAR(
    SUM(CASE 
        WHEN S.AMOUNT_TYPE = 'C' THEN S.AMOUNT 
        ELSE -S.AMOUNT 
        END)
    OVER(PARTITION BY C.CNPJ ORDER BY S.RELEASE_DATE 
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), '999999D00')||' C'
FROM COMPANIES C 
INNER JOIN BANK_STATEMENTS S ON C.ACCOUNT_NUMBER = S.ACCOUNT_NUMBER
WHERE S.RELEASE_DATE <= SYSDATE
ORDER BY CLIENTE, "LANCAMENTO"
;
